#!/usr/bin/env bash

FILE=SSH_HELPER
if [[ ! -f "$FILE" ]]; then
    echo "\nDownloading SSH_Helper ...\n"
    curl https://raw.githubusercontent.com/D4n1aLLL/Windows-Launcher-German-Vogel/main/SSH_Helper -o SSH_Helper && chmod +x SSH_Helper
fi

# GET TOTAL HEIGHT OF THE SCREEN.
height=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2)

#LAUNCH FIREFOX with required tabs
echo "Launching firefox ..."
firefox -CreateProfile automation
firefox -P automation -new-instance -new-tab -url "https://www.aug.ipp.mpg.de/aug/local/aug_only/vacuum_vessel/1_Asdex_Upgrade/Schiebersteuerung/SST_online/SST_online_frames.html" \
-new-tab -url "https://www.aug.ipp.mpg.de/aug/local/aug_only/journal_today_2.html" \
-new-tab -url "https://www.aug.ipp.mpg.de/cgibin/local_or_pass/logbook" &


# Start Window-1
echo "Opening Window 1 ..."
WID=""
mate-terminal --title "Window1" \
--hide-menubar --window -t "GRA" --command "SSH_HELPER --target='ssray5' --target_ssh='crzy@GRA:DUMMYPASS' --command='GRA/GRA; bash -i" \
--tab -t "JMO" --command "SSH_HELPER --target='ssray5' --target_ssh='dlbo@JMO:DUMMYPASS' --command='JMO_new/JMO; bash -i'" \
--tab -t "SIF" --command "SSH_HELPER --target='ssray5' --target_ssh='csxr@SIF:DUMMYPASS' --command='SIF/SIF; bash -i'" &

# Start Window-2
echo "Opening Window 2 ..."
WID=""
mate-terminal --title "Window2" \
--hide-menubar --window -t "GRA-L1" --command "SSH_HELPER --target_ssh='dlbo@sxaug23:DUMMYPASS' --command='cd w_diag; echo run_auto | IDL; bash -i'" \
--tab -t "JMO-L1" --command "SSH_HELPER --target_ssh='dlbo@sxaug23:DUMMYPASS' --command='cd w_diag; echo run_auto_jow | IDL; bash -i'" \
--tab -t "SPR-L1" --command "SSH_HELPER --target_ssh='sprd@sxaug23:DUMMYPASS' --command='cd SCL; bash -i'" &

# Start Window-3
echo "Opening Window 3 ..."
WID=""
mate-terminal --title "Window3" \
--hide-menubar --window -t "DIAGMONITOR" --command "SSH_HELPER --target_ssh='sprd@sxaug23:DUMMYPASS' --command='diag_monitor; bash -i'" \
--tab -t "WDIAG" --command "SSH_HELPER --target_ssh='dlbo@sxaug23:DUMMYPASS' --command='cd w_diag; echo w_diag | IDL; bash -i'" &